name: Déploiement API Boutique

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Déploiement sur le VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # Mise à jour du système
          sudo apt update && sudo apt upgrade -y
          
          # Installation des dépendances si nécessaire
          if ! command -v node &> /dev/null; then
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt install -y nodejs
          fi
          
          if ! command -v pm2 &> /dev/null; then
            sudo npm install -g pm2
          fi
          
          # Création du dossier de l'application
          sudo mkdir -p /var/www/api-boutique
          
          # Copie des fichiers
          cd /var/www/api-boutique
          git pull origin main || git clone ${{ secrets.REPO_URL }} .
          
          # Installation des dépendances
          npm install
          
          # Build du frontend
          npm run build
          
          # Configuration de Nginx
          sudo cp nginx.conf /etc/nginx/sites-available/api-boutique
          sudo ln -sf /etc/nginx/sites-available/api-boutique /etc/nginx/sites-enabled/
          sudo nginx -t && sudo systemctl restart nginx
          
          # Démarrage/Restart de l'application avec PM2
          pm2 start ecosystem.config.js --env production || pm2 restart api-boutique
          pm2 save
          
          # Vérification du statut
          pm2 status
          echo "✅ Déploiement terminé avec succès !" 