version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - DB_NAME=master
      - DB_USER=SA
      - DB_PASSWORD=BenjaminleGoat1!
      - DB_SERVER=mssql
      - DB_PORT=1433
      - JWT_SECRET=test
    depends_on:
      mssql:
        condition: service_healthy
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    platform: linux/arm64
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=BenjaminleGoat1!
      - MSSQL_PID=Developer
      - MSSQL_TCP_PORT=1433
    ports:
      - "1433:1433"
    command: /opt/mssql/bin/sqlservr
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "BenjaminleGoat1!" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 20s
    networks:
      - app-network
    user: mssql
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:

networks:
  app-network:
    driver: bridge
