version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - DB_NAME=master
      - DB_USER=SA
      - DB_PASSWORD=BenjaminleGoat1!
      - DB_SERVER=mssql
      - DB_PORT=1433
      - JWT_SECRET=test
    depends_on:
      - mssql
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=BenjaminleGoat1!
    ports:
      - "1433:1433"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
